### ISSUE TITLE
well how could i host the server on heroku ?

### ISSUE THREAD

**Issue by 0x41337** [BenMcH/node-grok#22]
how could i host it on heroku? when i tried it it just started. When I tried to use the client and tunnel my localhost it did not display the page on the port and was always loading. Would you help me ? @BenMcH

**Comment by BenMcH** [comment]
@J4c5 I built this project as more of a thought exercise than something that would be ideal to run in production. For various reasons, I do not believe you can run this on heroku. Mainly, the code assumes access to listen on various ports on the host system, something that I do not believe heroku supports. It could be run on a virtual server, like digital ocean or amazon ec2 with the correct firewall settings, but I make no guarantee that it will run well.

**Comment by 0x41337** [comment]
thanks for the answer, I don't have access to these servers and such, could I build something like ngrok and host on heroku?, I'm not that experienced..

**Comment by BenMcH** [comment]
I don't believe heroku allows you to use direct TCP ports, so this likely would not work unfortunately.
