### ISSUE TITLE
How does this compare to the Ngrox business plan?

### ISSUE THREAD

**Issue by danielpmc** [BenMcH/node-grok#3]
Hello,

Does this fully work? Looking at using it as a replacement of Ngrok business plan 

Thanks,
Dan

**Comment by BenMcH** [comment]
I believe that this would depend entirely on your use-case. This was a project that I threw together over the course of 2 days and does not have true tests outside of my own observations.

It will definitely work in some capacity, but it does not have all of the same features as ngrok. This will not give you request introspection, for example. It also relies on a small pool of ports, so you may need to make modifications to get it to suit your needs.

Feel free to submit a PR if this is lacking a feature that you'd like to add.

**Comment by danielpmc** [comment]
Hello,

I tried using it last night but was not able to get it to connect any idea? Also only using this to run some websites and ssh so hopefully it would work for that

**Comment by BenMcH** [comment]
Did you open the port range 20300-20399 on your server? What output were you seeing?

I wouldn't suggest running this for anything mission critical. It has no formal testing done other than a visual "yep it works" sitting in front of a webserver.

**Comment by danielpmc** [comment]
Hello! yes i did but when starting the "server" im getting nothing other than: 

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`

when looking in the code i should be also getting
  console.log('listening on *:8888');
but im not :/ 

Any idea what could be happening? and client keeps saying 
[nodemon] clean exit - waiting for changes before restart
but im going to guess thats because it cant connect to the server

**Comment by BenMcH** [comment]
How are you setting the project up? What is your node version? I can take a look at setting this up again to make sure that it works if need be.

**Comment by danielpmc** [comment]
i have tried Node version: v10.21.0 and v12.18.3 and had the same issue. 

Im not even able to get it to listen on the port. i removed all the code other than 
`const io = require('socket.io')();
io.listen(8888, function() {
  console.log('listening on *:8888');
});`

So i could make sure it was working and i dont get a response. so im sure its not even listening or starting it at all.

**Comment by BenMcH** [comment]
Are you able to run docker containers? If so, I could add a docker container to this repo to run the server with docker compose.

**Comment by danielpmc** [comment]
Yes

**Comment by BenMcH** [comment]
@danielpmc Can you check out my PR branch and verify that it is working for you? Once you've confirmed it, I can merge that into master. 

PR: #4

**Comment by danielpmc** [comment]
Getting a error: 
docker-compose up -d
Creating network "test_default" with the default driver
Building node-grok
Step 1/5 : FROM node:12.18.4-alpine
12.18.4-alpine: Pulling from library/node
cbdbe7a5bc2a: Pull complete
57d481011659: Pull complete
d6fabc993f17: Pull complete
834ca887ea10: Pull complete
Digest: sha256:757574c5a2102627de54971a0083d4ecd24eb48fdf06b234d063f19f7bbc22fb
Status: Downloaded newer image for node:12.18.4-alpine
 ---> 1f52b7199ba6
Step 2/5 : WORKDIR /app
 ---> Running in a19a642b1968
Removing intermediate container a19a642b1968
 ---> 522a7b0a61b6
Step 3/5 : ADD . .
 ---> 8ccb1dbe40d8
Step 4/5 : RUN npm install
 ---> Running in ab72c1d48d1c
npm WARN port-forward-server@0.0.1 No repository field.

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-02T01_03_49_098Z-debug.log
ERROR: Service 'node-grok' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by BenMcH** [comment]
That looks like a dns lookup timeout while installing node dependencies. Please try again

**Comment by danielpmc** [comment]
Ok. Yes can confirm that PR works.

**Comment by danielpmc** [comment]
Ok now getting a different problem. Running a website when i connect it works fine. i go to the website thats running and it allows me to connect. it then says "Connected" then "Connection closed" and doesnt work after that until i restart it. Any idea?

**Comment by BenMcH** [comment]
Do you have an application that I can test with? If we can reproduce, I'll take a look

**Comment by danielpmc** [comment]
I was just running a simple test website for the test ( [repo](https://github.com/danielpmc/testweb)  )

**Comment by BenMcH** [comment]
@danielpmc the connected and connection closed are simply saying that connections are coming in. They're debug statements. Feel free to ignore them. The website should still work. If you'd like to put them behind a debug flag in a PR, I'd gladly approve :smile:

**Comment by danielpmc** [comment]
Once you connect to the website and if you watch the client it should say connection closed. when it does if you try and access the website again does it let you?

**Comment by BenMcH** [comment]
Yes, I was able to navigate the site. I used pythons simple http server as my test ground today, so I'm also sure I didn't have client side rendering.

**Comment by BenMcH** [comment]
@danielpmc is there anything more that I can help answer about the project? If not, we can close the issue

**Comment by danielpmc** [comment]
Hello sorry iv been busy the last few days. ill get looking and see why im getting the issue. 

Ill go close this issue for now and if i need anything i will open a new issue or comment here
