### ISSUE TITLE
Convert npm to yarn

### ISSUE THREAD

**Issue by BenMcH** [BenMcH/node-grok#5]
I'd like to convert the client and server in this repo to use Yarn instead of NPM. 

Required steps:

* Update client lockfile
* Update server lockfile
* Update server Dockerfile and .dockerignore

**Comment by saravananselvamohan** [comment]
@BenMcH . Would like to work here on the issue

**Comment by BenMcH** [comment]
Thank you @saravananselvamohan! Go for it.

**Comment by BenMcH** [comment]
Accidentally merged the wrong PR. You'll still get credit for it. Thank you!
